// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: about_sections.sql

package queries

import (
	"context"
)

const listAboutSections = `-- name: ListAboutSections :many
SELECT id, key, content FROM about_sections ORDER BY key ASC
`

func (q *Queries) ListAboutSections(ctx context.Context) ([]AboutSection, error) {
	rows, err := q.db.Query(ctx, listAboutSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AboutSection
	for rows.Next() {
		var i AboutSection
		if err := rows.Scan(&i.ID, &i.Key, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
