// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bear_notes.sql

package queries

import (
	"context"
)

const listBearNotes = `-- name: ListBearNotes :many
SELECT id, title, excerpt, sort_order, content FROM bear_notes ORDER BY sort_order ASC
`

func (q *Queries) ListBearNotes(ctx context.Context) ([]BearNote, error) {
	rows, err := q.db.Query(ctx, listBearNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BearNote
	for rows.Next() {
		var i BearNote
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.SortOrder,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
