// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: desktop_items.sql

package queries

import (
	"context"
)

const listDesktopItems = `-- name: ListDesktopItems :many
SELECT id, name, type, parent_id, link, icon, sort_order FROM desktop_items ORDER BY sort_order ASC
`

func (q *Queries) ListDesktopItems(ctx context.Context) ([]DesktopItem, error) {
	rows, err := q.db.Query(ctx, listDesktopItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DesktopItem
	for rows.Next() {
		var i DesktopItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.Link,
			&i.Icon,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
