// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: education.sql

package queries

import (
	"context"
)

const listEducation = `-- name: ListEducation :many
SELECT id, school, degree, period_start, period_end, sort_order FROM education ORDER BY sort_order ASC
`

func (q *Queries) ListEducation(ctx context.Context) ([]Education, error) {
	rows, err := q.db.Query(ctx, listEducation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Education
	for rows.Next() {
		var i Education
		if err := rows.Scan(
			&i.ID,
			&i.School,
			&i.Degree,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
