// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: experience.sql

package queries

import (
	"context"
)

const listExperience = `-- name: ListExperience :many
SELECT id, company, role, period_start, period_end, description, sort_order FROM experience ORDER BY sort_order ASC
`

func (q *Queries) ListExperience(ctx context.Context) ([]Experience, error) {
	rows, err := q.db.Query(ctx, listExperience)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Experience
	for rows.Next() {
		var i Experience
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.Role,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Description,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
