// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: music.sql

package queries

import (
	"context"
)

const listMusic = `-- name: ListMusic :many
SELECT id, title, artist, cover, audio, sort_order FROM music ORDER BY sort_order ASC
`

func (q *Queries) ListMusic(ctx context.Context) ([]Music, error) {
	rows, err := q.db.Query(ctx, listMusic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Music
	for rows.Next() {
		var i Music
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Cover,
			&i.Audio,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
