// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package queries

import (
	"context"
)

const getProfile = `-- name: GetProfile :one
SELECT id, name, title, bio, avatar, email, phone, location, github, linkedin, updated_at FROM profile LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Bio,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.Location,
		&i.Github,
		&i.Linkedin,
		&i.UpdatedAt,
	)
	return i, err
}
