// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package queries

import (
	"context"
)

const listProjects = `-- name: ListProjects :many
SELECT id, title, excerpt, icon, live_url, markdown_file, sort_order, created_at, github_url, technologies FROM projects ORDER BY sort_order ASC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.Icon,
			&i.LiveUrl,
			&i.MarkdownFile,
			&i.SortOrder,
			&i.CreatedAt,
			&i.GithubUrl,
			&i.Technologies,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
