// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social_links.sql

package queries

import (
	"context"
)

const listSocialLinks = `-- name: ListSocialLinks :many
SELECT id, title, img, link, category, sort_order FROM social_links ORDER BY category ASC, sort_order ASC
`

func (q *Queries) ListSocialLinks(ctx context.Context) ([]SocialLink, error) {
	rows, err := q.db.Query(ctx, listSocialLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SocialLink
	for rows.Next() {
		var i SocialLink
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Img,
			&i.Link,
			&i.Category,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
