// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: typora_documents.sql

package queries

import (
	"context"
)

const getTyporaDocument = `-- name: GetTyporaDocument :one
SELECT id, title, content FROM typora_documents LIMIT 1
`

func (q *Queries) GetTyporaDocument(ctx context.Context) (TyporaDocument, error) {
	row := q.db.QueryRow(ctx, getTyporaDocument)
	var i TyporaDocument
	err := row.Scan(&i.ID, &i.Title, &i.Content)
	return i, err
}
