/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const AppWindow: typeof import('./components/AppWindow').default
  const AppleMenu: typeof import('./components/menus/AppleMenu').default
  const Battery: typeof import('./components/menus/Battery').default
  const Bear: typeof import('./components/apps/Bear').default
  const ControlCenterMenu: typeof import('./components/menus/ControlCenterMenu').default
  const Dock: typeof import('./components/dock/Dock').default
  const DockItem: typeof import('./components/dock/DockItem').default
  const FaceTime: typeof import('./components/apps/FaceTime').default
  const Finder: typeof import('./components/apps/Finder').default
  const Fragment: typeof import('react').Fragment
  const Launchpad: typeof import('./components/Launchpad').default
  const MenuItem: typeof import('./components/menus/base').MenuItem
  const MenuItemGroup: typeof import('./components/menus/base').MenuItemGroup
  const Safari: typeof import('./components/apps/Safari').default
  const Siri: typeof import('./components/apps/Siri').default
  const Spotify: typeof import('./components/apps/Spotify').default
  const Spotlight: typeof import('./components/Spotlight').default
  const Suspense: typeof import('react').Suspense
  const Terminal: typeof import('./components/apps/Terminal').default
  const TopBar: typeof import('./components/menus/TopBar').default
  const Typora: typeof import('./components/apps/Typora').default
  const VSCode: typeof import('./components/apps/VSCode').default
  const WifiMenu: typeof import('./components/menus/WifiMenu').default
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const forwardRef: typeof import('react').forwardRef
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const startTransition: typeof import('react').startTransition
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useAudio: typeof import('./hooks/useAudio').useAudio
  const useBattery: typeof import('./hooks/useBattery').useBattery
  const useCallback: typeof import('react').useCallback
  const useClickOutside: typeof import('./hooks/useClickOutside').useClickOutside
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useInterval: typeof import('./hooks/useInterval').useInterval
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useMemo: typeof import('react').useMemo
  const useOptimistic: typeof import('react').useOptimistic
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useStore: typeof import('./stores/index').useStore
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
  const useWindowSize: typeof import('./hooks/useWindowSize').useWindowSize
}
// for type re-export
declare global {
  // @ts-ignore
  export type { HTMLAudioState, HTMLAudioProps } from './hooks/useAudio'
  import('./hooks/useAudio')
  // @ts-ignore
  export type { BatteryState, UseBatteryState } from './hooks/useBattery'
  import('./hooks/useBattery')
}
